sports/events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.events, name='events'),
		# path('<int:id>/', views.detail, name='detail'),
]

sports/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.news, name='news'),
		path('<int:id>/', views.detail, name='detail'),
]

sports/sports/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('news/', include('news.urls')),
    path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sports/category/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']

sports/events/models.py
from django.db import models
from category.models import Category
from teams.models import Team


class Sponsor(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название')
    logo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Логотип', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Спонсор'
        verbose_name_plural = 'Спонсоры'
        ordering = ['name']


class Tournament(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название')
    prize_fund = models.IntegerField(verbose_name='Призовой фонд')
    sponsor = models.ForeignKey(Sponsor, on_delete=models.CASCADE, verbose_name='Спонсор')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Турнир'
        verbose_name_plural = 'Турниры'
        ordering = ['name']


class Event(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название')
    time = models.DateTimeField(verbose_name='Время проведения')
    result = models.CharField(max_length=64, verbose_name='Результат', blank=True)
    status = models.CharField(max_length=64, verbose_name='Статус')
    teams = models.ManyToManyField(Team, verbose_name='Команды')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, verbose_name='Турнир')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'
        ordering = ['name']

sports/news/models.py
from django.db import models
from django.contrib.auth.models import User
from category.models import Category


class News(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название')
    content = models.TextField(verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['created_at']

sports/podcasts/models.py
from django.db import models
from category.models import Category
from django.contrib.auth.models import User


class Podcast(models.Model):
    title = models.CharField(max_length=64, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    audio = models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Запись')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Подкаст'
        verbose_name_plural = 'Подкасты'
        ordering = ['title']

sports/teams/models.py
from django.db import models


class Type(models.Model):
    title = models.CharField(max_length=64, verbose_name='Тип команды')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тип команды'
        verbose_name_plural = 'Тип команд'
        ordering = ['title']


class Player(models.Model):
    name = models.CharField(max_length=64, verbose_name='Имя')
    surname = models.CharField(max_length=64, verbose_name='Фамилия')
    number = models.IntegerField(verbose_name='Номер')

    def __str__(self):
        return self.surname + ' ' + self.name

    class Meta:
        verbose_name = 'Игроки'
        verbose_name_plural = 'Игрок'
        ordering = ['surname', 'name']


class Team(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название')
    logo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Логотип', blank=True)
    players = models.ManyToManyField(Player, verbose_name='Игроки')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, verbose_name='Тип команды')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Команда'
        verbose_name_plural = 'Команды'
        ordering = ['name']

sports/category/views.py
from django.shortcuts import render

# Create your views here.

sports/events/views.py
from django.shortcuts import render

from .models import Event

def events(request):
	events = Event.objects.all()
	
	return render(request, 'events/list.html', {'events': events})

sports/news/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import News
from category.models import Category

def news(request):
	title = request.GET.get('title', '')
	category = request.GET.get('category', '')
	try:
		news = News.objects.filter(category__title__icontains=category, title__icontains=title)
		categoryes = Category.objects.all()
	except:
		raise Http404('Новость не найдена')

	return render(request, 'news/list.html', {'news': news, 'categoryes': categoryes})

def detail(request, id):
	try:
		news = News.objects.get(id = id)
	except:
		raise Http404('Новость не найдена')

	return render(request, 'news/detail.html', {'news': news})

sports/podcasts/views.py
from django.shortcuts import render

# Create your views here.

sports/teams/views.py
from django.shortcuts import render

# Create your views here.

sports/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'news:news' %}">Sports-news</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'news:news' %}">Новости</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:events' %}">Мероприятия</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
		<div class="container">
			{% block content %}{% endblock content %}
		</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

sports/templates/events/list.html
{% extends 'base.html' %}

{% block title %}Мероприятия{% endblock title %}

{% block content %}
	{% for e in events %}
		<div class="card mt-3">
			<div class="card-header d-flex justify-content-between">
				<div>{{e.name}}</div>
				<div>{{e.status}}</div>
			</div>
			<div class="card-body">
				<p class="card-text">
				Команды: {{e.teams}}
				</p>
				<a href="" class="btn btn-primary">Подробнее</a>
			</div>
		</div>
	{% endfor %}
{% endblock content %}

sports/templates/news/detail.html
{% extends 'base.html' %}

{% block title %}{{news.title}}{% endblock title %}

{% block content %}
	<h1 class="text-center mt-3">{{news.title}}</h1>
	<p>{{news.content}}</p>
	<a href="{% url 'news:news' %}">Назад</a>
{% endblock content %}

sports/templates/news/list.html
{% extends 'base.html' %}
{% block title %}Новости{% endblock title %}

{% block content %}
	<div class="row">
		<div class="col">
			<form action="{% url 'news:news' %}" method="get" class="mt-3">
				<div class="row">
					<div class="col-auto">
						<input type="text" class="form-control" placeholder="Поиск" name="title">
						</div>
					<div class="col-auto">
							<button type="submit" class="btn btn-primary">Поиск</button>
					</div>
					<div class="col-auto">
						<select class="form-select" name="category">
							<option value="" selected>Категория</option>
							{% for c in categoryes %}
							<option value="{{c.title}}">{{c.title}}</option>
							{% endfor %}
						</select>
					</div>
				</div>
			</form>
		</div>
	</div>

	{% for n in news %}
		<div class="card mt-3">
			<div class="card-header">
				{{n.category}}
			</div>
			<div class="card-body">
				<h5 class="card-title">{{n.title}}</h5>
				<p class="card-text">{{n.content}}</p>
				<a href="{% url 'news:detail' n.id %}" class="btn btn-primary">Подробнее</a>
			</div>
		</div>
	{% endfor %}
{% endblock content %}